<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GetProjectCount</name>
   <tag></tag>
   <elementGuidId>9f51e27f-bec6-47e2-89d2-0aefb82c97dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table//tbody/tr/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table//tbody/tr/td[1]</value>
   </webElementProperties>
</WebElementEntity>
