<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SettingsBtn_Click</name>
   <tag></tag>
   <elementGuidId>1dca83ae-97f0-4df6-bab3-6966bdcab7e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button/span/mat-icon[text()='settings']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button/span/mat-icon[text()='settings']</value>
   </webElementProperties>
</WebElementEntity>
