<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ClickPlusIcon</name>
   <tag></tag>
   <elementGuidId>5ce83b9d-fddc-42ea-940b-e44c25f693eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//mat-icon[text()='add']/parent::span/parent::button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//mat-icon[text()='add']/parent::span/parent::button</value>
   </webElementProperties>
</WebElementEntity>
